//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR_LOG
    {
        public System.Guid id { get; set; }
        public string file_name { get; set; }
        public string method_name { get; set; }
        public string source { get; set; }
        public string stack_trace { get; set; }
        public string inner_exception { get; set; }
        public string message { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.Guid> create_by { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
