//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOME_NAVIGATION
    {
        public System.Guid id { get; set; }
        public System.Guid navigation_id { get; set; }
        public short ordering { get; set; }
    
        public virtual NAVIGATION NAVIGATION { get; set; }
    }
}
