//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_ACCOUNT()
        {
            this.MM_ACCOUNT_HISTORY = new HashSet<MM_ACCOUNT_HISTORY>();
            this.MM_INCOME = new HashSet<MM_INCOME>();
            this.MM_PAYMENT = new HashSet<MM_PAYMENT>();
            this.MM_TRANSFER = new HashSet<MM_TRANSFER>();
            this.MM_TRANSFER1 = new HashSet<MM_TRANSFER>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid account_type_id { get; set; }
        public string name { get; set; }
        public decimal start { get; set; }
        public decimal input { get; set; }
        public decimal output { get; set; }
        public decimal end { get; set; }
        public decimal ordering { get; set; }
        public bool publish { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_ACCOUNT_HISTORY> MM_ACCOUNT_HISTORY { get; set; }
        public virtual MM_ACCOUNT_TYPE MM_ACCOUNT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_INCOME> MM_INCOME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_PAYMENT> MM_PAYMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_TRANSFER> MM_TRANSFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_TRANSFER> MM_TRANSFER1 { get; set; }
    }
}
