//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MN_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MN_CATEGORY()
        {
            this.MN_CATEGORY_SETTING = new HashSet<MN_CATEGORY_SETTING>();
            this.MN_INCOME = new HashSet<MN_INCOME>();
            this.MN_PAYMENT = new HashSet<MN_PAYMENT>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string notes { get; set; }
        public System.Guid group_id { get; set; }
        public byte percent_setting { get; set; }
        public byte percent_current { get; set; }
        public decimal money_setting { get; set; }
        public decimal money_current { get; set; }
        public decimal startmonth { get; set; }
        public decimal endmonth { get; set; }
        public short ordering { get; set; }
        public bool publish { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        public virtual MN_GROUP MN_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MN_CATEGORY_SETTING> MN_CATEGORY_SETTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MN_INCOME> MN_INCOME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MN_PAYMENT> MN_PAYMENT { get; set; }
    }
}
