//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ROLE
    {
        public System.Guid id { get; set; }
        public System.Guid user_id { get; set; }
        public System.Guid role_id { get; set; }
    
        public virtual ROLE ROLE { get; set; }
        public virtual USER USER { get; set; }
    }
}
