//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MN_ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MN_ACCOUNT()
        {
            this.MN_ACCOUNT_SETTING = new HashSet<MN_ACCOUNT_SETTING>();
            this.MN_INCOME = new HashSet<MN_INCOME>();
            this.MN_PAYMENT = new HashSet<MN_PAYMENT>();
            this.MN_TRANSFER = new HashSet<MN_TRANSFER>();
            this.MN_TRANSFER1 = new HashSet<MN_TRANSFER>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid account_type_id { get; set; }
        public string name { get; set; }
        public decimal start { get; set; }
        public decimal input { get; set; }
        public decimal output { get; set; }
        public decimal end { get; set; }
        public decimal ordering { get; set; }
        public bool publish { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
        public decimal max_payment { get; set; }
    
        public virtual MN_ACCOUNT_TYPE MN_ACCOUNT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MN_ACCOUNT_SETTING> MN_ACCOUNT_SETTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MN_INCOME> MN_INCOME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MN_PAYMENT> MN_PAYMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MN_TRANSFER> MN_TRANSFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MN_TRANSFER> MN_TRANSFER1 { get; set; }
    }
}
