//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_DETAIL
    {
        public System.Guid id { get; set; }
        public System.Guid role_id { get; set; }
        public string function_code { get; set; }
        public bool view { get; set; }
        public bool add { get; set; }
        public bool edit { get; set; }
        public bool delete { get; set; }
    
        public virtual FUNCTION FUNCTION { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
