//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER_TOKEN
    {
        public System.Guid id { get; set; }
        public System.Guid user_id { get; set; }
        public bool is_mobile { get; set; }
        public string platform { get; set; }
        public string version { get; set; }
        public string user_agent { get; set; }
        public string host_name { get; set; }
        public string host_address { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime expire_time { get; set; }
        public Nullable<bool> state { get; set; }
        public string token { get; set; }
        public string session_id { get; set; }
    
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
