//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_FUNCTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_FUNCTION()
        {
            this.SYS_ROLE_DETAIL = new HashSet<SYS_ROLE_DETAIL>();
        }
    
        public string code { get; set; }
        public string name { get; set; }
        public string area { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public short ordering { get; set; }
        public string title { get; set; }
        public string module_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_ROLE_DETAIL> SYS_ROLE_DETAIL { get; set; }
        public virtual SYS_MODULE SYS_MODULE { get; set; }
    }
}
