//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARGET_TASK
    {
        public System.Guid id { get; set; }
        public System.Guid target_id { get; set; }
        public string title { get; set; }
        public string result { get; set; }
        public bool done { get; set; }
        public System.DateTime estimate_date { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        public virtual TARGET TARGET { get; set; }
    }
}
