//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MN_REPORT_BORROW_ACCOUNT_STATUS
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public decimal max_payment { get; set; }
        public Nullable<decimal> remain { get; set; }
        public string title { get; set; }
        public decimal money { get; set; }
        public System.DateTime date { get; set; }
    }
}
