//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYS_RENDER_NAVIGATION
    {
        public string module_code { get; set; }
        public string module_title { get; set; }
        public string default_action { get; set; }
        public string icon { get; set; }
        public short module_order { get; set; }
        public string code { get; set; }
        public string url { get; set; }
        public short ordering { get; set; }
        public string title { get; set; }
        public short function_ordering { get; set; }
        public System.Guid id { get; set; }
    }
}
