//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TIMELINE
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string school { get; set; }
        public string duration { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
        public bool is_plan { get; set; }
        public bool is_finish { get; set; }
        public bool is_cancel { get; set; }
        public string type_code { get; set; }
        public string type_name { get; set; }
        public System.Guid created_by { get; set; }
    }
}
