//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDH.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WK_CHECKLIST_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WK_CHECKLIST_ITEM()
        {
            this.WK_CHECKLIST_ITEM_DETAIL = new HashSet<WK_CHECKLIST_ITEM_DETAIL>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid group_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.Guid create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.Guid> delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        public virtual WK_CHECKLIST_GROUP WK_CHECKLIST_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WK_CHECKLIST_ITEM_DETAIL> WK_CHECKLIST_ITEM_DETAIL { get; set; }
    }
}
